// Package dynamicwatch registers a controller-runtime watch on a Kind whose GroupVersionKind is not
// known until runtime (e.g. a CRD generated by another controller), deduping repeated registration
// attempts for the same GVK. It is modeled on the watch-registration mechanics proven in
// core-provider's compositionmirror reconciler: capture the controller.Controller returned by
// Builder.Build (not Complete, which discards it), then call Watch on it — safe even after the
// manager/controller has started — the first time a runtime-discovered Kind is seen.
package dynamicwatch

import (
	"sync"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/source"
)

// Registry tracks which GroupVersionKinds already have a registered watch, so a caller that reconciles
// many owners of the same runtime-discovered Kind can call EnsureWatch on every reconcile without
// registering a duplicate watch for a Kind it has already seen.
type Registry struct {
	cache cache.Cache

	mu      sync.Mutex
	watched map[schema.GroupVersionKind]struct{}
}

// NewRegistry returns a Registry backed by the given cache (typically mgr.GetCache()).
func NewRegistry(c cache.Cache) *Registry {
	return &Registry{cache: c, watched: map[schema.GroupVersionKind]struct{}{}}
}

// EnsureWatch registers a watch on gvk the first time it is seen; later calls for the same gvk are
// no-ops. mapFunc maps an event on an instance of gvk to the reconcile.Requests it should enqueue.
//
// Registration is best-effort by design: if gvk is not yet discoverable (e.g. its CRD was only just
// created), the underlying Watch call returns an error, which EnsureWatch propagates WITHOUT marking gvk
// as watched — so the caller's next reconcile retries registration.
//
// There is no corresponding "unwatch": controller-runtime has no primitive to remove a source from a
// running controller. A watch on a GVK that later stops being needed is harmless (its informer simply
// idles) but is never released for the life of the process — an accepted tradeoff, not an oversight.
func (r *Registry) EnsureWatch(ctrl controller.Controller, gvk schema.GroupVersionKind, mapFunc handler.MapFunc, predicates ...predicate.Predicate) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	if _, ok := r.watched[gvk]; ok {
		return nil
	}

	obj := &unstructured.Unstructured{}
	obj.SetGroupVersionKind(gvk)
	var co client.Object = obj

	src := source.Kind(r.cache, co, handler.EnqueueRequestsFromMapFunc(mapFunc), predicates...)
	if err := ctrl.Watch(src); err != nil {
		return err
	}
	r.watched[gvk] = struct{}{}
	return nil
}

// Watching reports whether gvk currently has a registered watch.
func (r *Registry) Watching(gvk schema.GroupVersionKind) bool {
	r.mu.Lock()
	defer r.mu.Unlock()
	_, ok := r.watched[gvk]
	return ok
}
